version: "3.4"
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    env_file: docker/docker.env
    environment:
      - "WAIT_HOSTS=db:5432"
    entrypoint: docker/entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=db_password"
      - "POSTGRES_USER=db_user"
      - "POSTGRES_DB=db_dbname"
