"""creating title field

Revision ID: 97da1d7154f4
Revises: 12d06d7dd6d1
Create Date: 2023-04-27 20:06:44.461873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97da1d7154f4'
down_revision = '12d06d7dd6d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uri', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uri', 'title')
    # ### end Alembic commands ###
